env:
  global:
    secure: FS/TOcFeLcvij98Bw1lv40LhwLLACxyFjL9FMX3ZvMQeG5pjJp/mNlt6ZGvhucah2+VF0PpG0PRYpRAAND5gGPi+kK87TayBUnDWK2WjmAnpYrxWWBaCtXAEDk+ZG/7fa5Pl8k8WDpa0XAfWVi/5x5VM0EjWZFBlA/eDofGwS8ea0StC7Re+fZGAueeY+CHTZ7c4rN0T/fuHediSOfjglsOFmGGS/CBkG47COi67gU0llhlrea/6G5KoWDsuUx6rsm0iAyR9tP3JV63FFXMlRhl/ELZns/n7A6qqMTE4Ig0Pr9KMgsatBGdIGaKoRCXbAJycxvmWyFCQ6f40rvmhXV0+9FGC/uGv5WX//hDxdLF3T87+anGEUr99NOIJGg74VdnhVeKCSQZEroUccjO9D7hiRdDoRfavXMd1T9z7Zj2QktnmZTU/4j7RdYl2GQCYaZgfK5dQYS2Xv7KzJXs5/tRQxivOv6oEM7gASg4yiln9OSuRx7NV8TzA/LWB/Uku5yUjF4jqGtt01DCch57wxdCeEghEaCloPDZBttqORg0WHcywIcSa5U5vtKUxTZ5QpLPXVzhYYmp4USpeid4QQMXrbGSpA67FH843SYFjXGcJLqgNfDB2H2z97SLPc5YVIguzu7ya3tDOUwG/LDnd116UbszgCuGH8eQg36zhNEA=
language: node_js
node_js:
- stable
script:
- npm test -- --coverage
- npm install codecov -g
- codecov
deploy:
  provider: npm
  email: danielpza@protonmail.com
  api_key:
    secure: vP1eYbg096YZBzDLj7vZYJlyo8Fqw2xwTrMATRdpcFUyCm1PJ8M2I+ehzuDtWoHektiW/FhWJC0WfkpjU7r4M+WquPz6av7qNh0a/huOrH/huPt1EIUnhzI+1A4S3bzmZtJpsnA28m8+KZQAVKwrS18/sJTOBNvXu5uqUDCSWGe8cu6Bma1ecLKul/hJ2oGO4uzTFWDlSHAOWaj39Mi6zbim/BBxUY3C7/JEWnWIHoURqyubDsHO3yKBHxCHkFs0va7114f7NyFJaeJKQ6U/yMiGB+/u20rSEJenWdIi5R+mhy79uh2RiTDqMLyQK932NuQ/7NvROHFX77KF1QMVgEEcXdNZdUqvs7UGCvKmu6M3oFpWkLUXvjpwd4AMKsmjW+Z/Xbw+OOiBNR40hSMwgdOnYObcvYG6jhZy1vNKbxHJDcxB9Snh+myC0zm1knHyqMBauVQTN4c8fUjOJOP4Su6tstBTVoXYs+dTVkRKr0G7Itv9Fw7e86tY71oHkX6w572G42jGJZ9IOqrJiD1+8dHPx+++KhnnXACZTxq7C3Yq8ewJOCqY+pQDoPx9dtBLqdG5tVWB0VG4A+PH7HZcF7rM0RA1rTC43tYRasPC4MfaSBY2cKuRYdcVckAK8XDdpzrcgk7e3DLtPfcYLCkPAmtq2mUmnhPxjYWOCIJ89M0=
  on:
    tags: true
    repo: LeDDGroup/typescript-transform-macros
